import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import { LanguageProvider } from "@/components/contexts/LanguageContext";
import Banner from "@/components/about/Banner";
import About from "@/components/about/About";
import Expert from "@/components/about/Expert";

export default function Services() {
  return (
    <LanguageProvider>
      <Head>
        <title>O.C.T | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner/>
        <About/>
        <Expert/>
      </main>
      <Footer />
    </LanguageProvider>
  );
}
