import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import { LanguageProvider } from "@/components/contexts/LanguageContext";

import Banner from "@/components/gallery/Banner";
import Info from "@/components/gallery/Info";
import Series from "@/components/gallery/Series";
import Album from "@/components/gallery/Album";
import { useState } from "react";

export default function Services() {
  const [isOpenSeries, setIsOpenSeries] = useState(false);
  const [series, setSeries] = useState(null);

  return (
    <LanguageProvider>
      <Head>
        <title>O.C.T | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main >
        <Banner />
        <Info />
        {!isOpenSeries ? (<Series setIsOpenSeries={setIsOpenSeries} setSeries={setSeries} />) : (<Album series={series} setIsOpenSeries={setIsOpenSeries} setSeries={setSeries} />)}
        
  
      </main>
      <Footer />
    </LanguageProvider>
  );
}
