import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import { LanguageProvider } from "@/components/contexts/LanguageContext";
import UsefulLinks from "@/components/UsefulLinks";
import Banner from "@/components/give/Banner";
import Program from "@/components/services/Program";
import Time from "@/components/services/Time";
import Quote from "@/components/give/Quote";
import InfoGive from "@/components/give/InfoGive";

export default function Services() {
  return (
    <LanguageProvider>
      <Head>
        <title>O.C.T | Give</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main >
        <Banner />
        <Quote />
        <InfoGive />
      </main>
      <Footer />
    </LanguageProvider>
  );
}
