import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import { LanguageProvider } from "@/components/contexts/LanguageContext";
import UsefulLinks from "@/components/UsefulLinks";
import Banner from "@/components/home/Banner";
import Schedule from "@/components/home/Schedule";
import Annonce from "@/components/home/Annonce";
import Daily from "@/components/home/Daily";
import Event from "@/components/home/Event";
import Service from "@/components/home/Service";
export default function Home() {
  return (
    <LanguageProvider>
      <Head>
        <title>Ottawa Christian Tabernacle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner />
        <Daily />
        <Event />
        <Service />

      </main>
      <Footer />
    </LanguageProvider>
  );
}
