import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import { LanguageProvider } from "@/components/contexts/LanguageContext";
import Banner from "@/components/sermons/Banner";
import Sermons from "@/components/sermons/Sermons";
import Lecture from "@/components/sermons/Lecture";


export default function Services() {
  return (
    <LanguageProvider>
      <Head>
        <title>O.C.T | Sermons</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
      <Banner/>
      <Sermons/>
      <Lecture/>
      </main>
      <Footer />
    </LanguageProvider>
  );
}
