import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import { LanguageProvider } from "@/components/contexts/LanguageContext";
import Banner from "@/components/visit/Banner";
import Visit from "@/components/visit/Visit";
import Map from "@/components/visit/Map";


export default function VisitUs() {
  return (
    <LanguageProvider>
      <Head>
        <title>Voice of God Tabernacle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Banner />
        <Visit />
        <Map />
      </main>
      <Footer />
    </LanguageProvider>
  );
}
