
import Head from "next/head";
import Sidemenu from "./components/home/Sidemenu";
import Home from "./components/home/Home";


export default function Services() {
  return (
    <>
      <Head>
        <title>O.C.T | Give</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main >
        <Sidemenu/>
      </main>
    
    </>
  );
}
