import Head from "next/head";
import LoginAdmin from "./components/login/Login";


export default function Login() {
  return (
    <>
      <Head>
        <title>O.C.T | Login-Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main >
        <LoginAdmin/>
      </main>
    
    </>
  );
}
